name: showcaseview
description: A Flutter package to Showcase/Highlight widgets step by step.
version: 1.1.1
homepage: https://github.com/simformsolutions/flutter_showcaseview
issue_tracker: https://github.com/simformsolutions/flutter_showcaseview/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ombre_widget_package:
    git:
      url: https://github.com/ombreapp/ombre-flutter-components.git
      ref: nonNullSafety
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.2

flutter:
  fonts:
    - family: PlayfairDisplay-Regular
      fonts:
        - asset: font/PlayfairDisplay-Regular.ttf

    - family: PlayfairDisplay-Bold
      fonts:
        - asset: font/PlayfairDisplay-Bold.ttf

    - family: Poppins-Regular
      fonts:
        - asset: font/Poppins-Regular.ttf

    - family: Poppins-Bold
      fonts:
        - asset: font/Poppins-Bold.ttf
